# pandas 入門

In [17]:
# Library の import

# NumPy用 Library
import numpy as np

# pandas用 Library
import pandas as pd

# DataFrame表示用関数
# from IPython.display import display

# DataFrame での表示精度
pd.options.display.float_format = '{:.4f}'.format

# DataFrame ですべての項目を表示
pd.set_option("display.max_columns", None)

In [18]:
# ２次元 NumPy 配列の定義
b = np.array([[1, 2, 1], [4, 5, 2], [7, 8, 2], [10, np.nan, 1], [13, 10, 2]])

# 結果確認
print(b)

[[ 1.  2.  1.]
 [ 4.  5.  2.]
 [ 7.  8.  2.]
 [10. nan  1.]
 [13. 10.  2.]]


In [19]:
# DataFrame の定義
df = pd.DataFrame(b, columns=['col_a', 'col_b', 'col_c'])

# 型表示
print(type(df))

# display 関数による整形表示
display(df)

<class 'pandas.core.frame.DataFrame'>


col_a   col_b  col_c
0  1.0000  2.0000 1.0000
1  4.0000  5.0000 2.0000
2  7.0000  8.0000 2.0000
3 10.0000     NaN 1.0000
4 13.0000 10.0000 2.0000

In [20]:
# DataFrame の各部品表示

# 列名
print('列名', df.columns)
print('行名', df.index)

# Data本体
print('Data本体\n', df.values)

列名 Index(['col_a', 'col_b', 'col_c'], dtype='object')
行名 RangeIndex(start=0, stop=5, step=1)
Data本体
 [[ 1.  2.  1.]
 [ 4.  5.  2.]
 [ 7.  8.  2.]
 [10. nan  1.]
 [13. 10.  2.]]


In [22]:
# CSV File からの読み込み

# 読み込み元 URL
csv_url = 'https://raw.githubusercontent.com/makaishi2/sample-data/master/data/df-sample.csv'

# Data 読み込み
df_csv = pd.read_csv(csv_url)

# 結果確認
display(df_csv)

col_a   col_b  col_c
0  1.0000  2.0000 1.0000
1  4.0000  5.0000 2.0000
2  7.0000  8.0000 2.0000
3 10.0000     NaN 1.0000
4 13.0000 10.0000 2.0000

In [23]:
# File 読み込み後の列名変更
columns = ['A列', 'B列', 'C列']
df_csv.columns = columns

# 結果確認
display(df_csv)

A列      B列     C列
0  1.0000  2.0000 1.0000
1  4.0000  5.0000 2.0000
2  7.0000  8.0000 2.0000
3 10.0000     NaN 1.0000
4 13.0000 10.0000 2.0000